name: Static Analysis
on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install FVM
        run: |
          brew tap leoafarias/fvm
          brew install fvm
          echo "$HOME/fvm/default/bin" >> $GITHUB_PATH
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
          fvm install 3.10.0 --setup
          fvm install stable --setup
          fvm global 3.10.0
          flutter doctor
          fvm global stable
          flutter doctor
      - name: Pub get
        run: dart pub get
      - name: Format
        run: dart format --set-exit-if-changed .
      - name: Analyze
        run: dart analyze --fatal-infos
      - name: custom_lint
        run: dart run custom_lint
      - name: Test
        run: dart test
      - name: Pana
        run: |
          dart pub global activate pana
          pana --no-warning --exit-code-threshold 0
